# Generated by Django 3.2.7 on 2021-09-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_sender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
    ]
